export const GET_ITEMS = "GET_ITEMS";
export const ADD_ITEMS = "ADD_ITEMS";
export const DELETE_ITEMS = "DELETE_ITEMS";
export const GET_ITEMS_FAIL = "GET_ITEMS_FAIL";
export const ITEMS_LOADING = "ITEMS_LOADING";


export const GET_RECIPE_ITEMS = "GET_RECIPE_ITEMS";
export const ADD_RECIPE_ITEMS = "ADD_RECIPE_ITEMS";
export const DELETE_RECIPE_ITEMS = "DELETE_RECIPE_ITEMS";
export const GET_RECIPE_ITEMS_FAIL = "GET_RECIPE_ITEMS_FAIL";
export const ITEMS_RECIPE_LOADING = "ITEMS_RECIPE_LOADING";

export const GET_POST_ITEMS = "GET_POST_ITEMS";
export const ADD_POST_ITEMS = "ADD_POST_ITEMS";
export const DELETE_POST_ITEMS = "DELETE_POST_ITEMS";
export const GET_POST_ITEMS_FAIL = "GET_POST_ITEMS_FAIL";
export const ITEMS_POST_LOADING = "ITEMS_POST_LOADING";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const PUBLISH_SUCCESS = "PUBLISH_SUCCESS";
export const PUBLISH_FAIL = "PUBLISH_FAIL";

export const POST_SUCCESS = "POST_SUCCESS";
export const POST_FAIL = "POST_FAIL";
